### ISSUE TITLE
caching with distributed

### ISSUE THREAD

**Issue by ordirules** [mrocklin/streams#10]
I'm not sure where to post this but I think it seems to have something to do with streams.
There must be something fundamental I don't understand of distributed. I
would expect the following to result in a cached result on the cluster:

```python
    from distributed import Client
    from streams import Stream
    from dask import delayed

    client = Client("xx.xx.x.x:xxxxx")
    client.has_what()

    #output: {'tcp://xx.xx.x.x:xxxxx': []}

    s = Stream(); sout = s.map(delayed).map(lambda x : x).map(client.compute)

    s.emit(10)
    client.has_what()
    #output: {'tcp://xx.xx.x.x:xxxxx': []}

    s = Stream(); sout = s.map(delayed).map(lambda x : x).map(client.compute).map(print)

    s.emit(10)
    #output: <Future: status: pending, key: finalize-30855c9e1ecca7881ff1355bbe9335e7>

    client.has_what()
    #output: {'tcp://xx.xx.x.x:xxxxx': []}

```
However, as you can see, the output is nothing.

On the other hand, this works:
```python
    from distributed import Client
    from streams import Stream
    from dask import delayed

    client = Client("xx.xx.x.x:xxxxx")

   
    client.compute(delayed(lambda x : x))

    client.has_what()
    #output {'tcp://xx.xx.x.x:xxxxx': ['finalize-2e05de10e50701fc34ec28edcdf03599']}
```

Do you know what is possibly happening? I have given a quick look and
don't see anything obvious. This issue may be deeper than my current
understanding of distributed.

**Comment by mrocklin** [comment]
http://distributed.readthedocs.io/en/latest/memory.html

When your futures go away they get garbage collected

**Comment by mrocklin** [comment]
Try sinking the futures to a list

**Comment by ordirules** [comment]
it works:
```python
s = Stream(); sout = s.map(delayed).map(lambda x : x).map(client.compute).sink_to_list()
```
I might use a queue or LRU cache for the list. (I guess a queue should be fine since a queue of futures is like an LRU if I understand correclty)
I think what confused me is that in the non-stream case, I'm not storing the future from the `client.compute` somewhere.

Would you know by any chance why this one is not being garbage collected? I also noticed inconsistent results for this. (some times the cache would grow, sometimes not, and just replace a parameter). I am just curious. Might be worth warning about this in docs too.

thanks!

**Comment by mrocklin** [comment]
The futures are now being placed into a list, which  you are calling sout.
For as long as those futures are in your local session dask will endeavor
to keep the data in distributed memory.  (See the docpage referenced
before).  If you want something like LRU then you might try a deque

    futures = deque(maxlen=100)
    stream.sink(futures.append)

**Comment by ordirules** [comment]
just to be clear i was talking about this line:
'''python
   
    client.compute(delayed(lambda x : x))
'''
the results are getting cached on the machine. is this intended? thanks again for the response
(excuse my brevity sent from a mobile)

**Comment by mrocklin** [comment]
No, I don't know.  Maybe it just hasn't gotten the message yet?  If you are in IPython or jupyter then it stores the outputs of every cell.  That could be it as well.

**Comment by ordirules** [comment]
ah yes, that's it, I forget about those magical `_...` variables. it also explains the maximum size of the cache.
thanks!
