### ISSUE TITLE
Best way to emit more than came in

### ISSUE THREAD

**Issue by CJ-Wright** [mrocklin/streams#23]
Is it possible to emit more things than were put into the stream?

**Comment by mrocklin** [comment]
Yes.  Update and emit are not in any way tied.

To support backpressure make sure that you return a list of whatever comes back from emit.  If they are lists then you'll want to flatten them.

```python
class Double(Steam):
    def update(self, x, who=None):
        a = self.emit(x)
        b = self.emit(x)
        L = []
        for x in [a, b]:
            if isinstance(x, list):
                L.extend(x)
            else:
                L.append(x)
        return L

```

**Comment by mrocklin** [comment]
The packing logic could probably be centralized someplace if this were to become commonplace

**Comment by CJ-Wright** [comment]
This works
