### ISSUE TITLE
Push to master

### ISSUE THREAD

**Issue by CJ-Wright** [mrocklin/streams#33]
@mrocklin I seem to have pushed to master by accident, do you want a revert and PR or is the code ok
Sorry :frowning:

**Comment by CJ-Wright** [comment]
On the bright side it passes the tests/flake8
https://travis-ci.org/mrocklin/streams

**Comment by mrocklin** [comment]
I didn't notice and don't care.  Seems like a good change.  The project is relatively small and, for as long as it's relatively unused then if you have high confidence that everyone will be happy with the change then please feel free to play things fast and loose.
